<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8;net472</TargetFrameworks>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<GenerateAssemblyInfo>False</GenerateAssemblyInfo>
		<Deterministic>False</Deterministic>
		<Platforms>AnyCPU;x64;ARM64;x86</Platforms>
		<SignAssembly>True</SignAssembly>
		<AssemblyOriginatorKeyFile>keypair.snk</AssemblyOriginatorKeyFile>
		<LangVersion>preview</LangVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<WeaverConfiguration>
			<Weavers>
				<InlineIL />
			</Weavers>
		</WeaverConfiguration>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<Optimize>True</Optimize>
		<DebugType>none</DebugType>
		<WeaverConfiguration>
			<Weavers>
				<InlineIL />
				<InlineMethod />
				<LocalsInit />
				<Absence />
			</Weavers>
		</WeaverConfiguration>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\GlobalAssemblyInfo.cs" Link="GlobalAssemblyInfo.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Fody" Version="6.9.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="InlineIL.Fody" Version="1.10.2">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="InlineMethod.Fody" Version="0.8.7">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Absence.Fody" Version="2.0.11">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="LocalsInit.Fody" Version="1.1.0">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="PolySharp" Version="1.16.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net472'">
		<PackageReference Include="System.Numerics.Vectors" Version="4.6.1" />
		<!-- Only for develop use!-->
		<PackageReference Include="System.Buffers" Version="4.6.1">
			<PrivateAssets>all</PrivateAssets>
			<ExcludeAssets>runtime</ExcludeAssets>
			<IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="System.Memory" Version="4.6.3">
			<PrivateAssets>all</PrivateAssets>
			<ExcludeAssets>runtime</ExcludeAssets>
			<IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3">
			<PrivateAssets>all</PrivateAssets>
			<ExcludeAssets>runtime</ExcludeAssets>
		</PackageReference>
		<PackageReference Include="RiceTea.Backport.System.Runtime.Intrinsics" Version="1.0.13" />
	</ItemGroup>

	<PropertyGroup Condition="'$(Platform)'=='AnyCPU'">
		<DefineConstants>$(DefineConstants);ANYCPU</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Platform)'=='x64'">
		<DefineConstants>$(DefineConstants);B64_ARCH;X86_ARCH</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Platform)'=='x86'">
		<DefineConstants>$(DefineConstants);B32_ARCH;X86_ARCH</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Platform)'=='ARM64'">
		<DefineConstants>$(DefineConstants);B64_ARCH;ARM_ARCH</DefineConstants>
	</PropertyGroup>
	
</Project>
